# Generated by Django 6.0.1 on 2026-01-14 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='proof_files',
            field=models.FileField(blank=True, null=True, upload_to='claims/proofs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
